### ISSUE TITLE
High End Systems Hog4 

### ISSUE THREAD

**Issue by ghost** [bitfocus/companion-module-highend-hog4#3]
**Describe the feature**
Control over programmed Scenes etc.

**Is this platform dependent (windows, mac, ..)?**
No, OSC

**If documentation is required to implement, do you know where to find it?**
https://www.highend.com/documentation/HOG4/H4_manual.pdf , page 379 ff.

**Usecases**
Control over Lighting systems...

**Comment by willosof** [comment]
I moved this out from the main repo @krocheck :)

**Comment by krocheck** [comment]
@Lichtbau the hardware buttons you requested are in the "Hardware Key" action.  I organized them by the key groups rather than alphabetical.  I should probably revisit that sorting.

**Comment by krocheck** [comment]
@Lichtbau any updates?

**Comment by Lichtbau** [comment]
tested with hedgehog4 x / hog os 3.10.0 (b 1809).
hardware buttons tested and all working.
hedgehog has no restore/rate button but midi viewer shows good values for both.

**Comment by Lichtbau** [comment]
tested with hedgehog4 x / hog os 3.10.0 (b 1809).
# some key combinations tested.
works:
patch ( OPEN + FIXTURE ),
swop from kind to commands ( PIG + ENTER ),
fade changes ( PIG + BLIND ),
undo ( PIG + CLEAR ),
invert kind masking ( PIG + MERGE ) for merge or ( PIG + RECORD ),
close window ( PIG + BACKSPACE ),
unpatch @ ( PIG + @ ),
aktive window full screen ( OPEN + FULL ),
colour Picker ( PIG + OPEN + COLOUR ),
media Picker ( PIG + OPEN + BEAM ),
window to next screen ( OPEN + @ ),
open view ( OPEN + "Digit" ).

not working:
generate plot keyword in commandline ( PIG + FIXTURE ) but works with indiv. single buttons,
cycles through open windows - change focus ( OPEN + THRU ) but works with indiv. single buttons,
windows copy / splitt ( OPEN + / ) but works with indiv. single buttons,
open batch window ( PIG + OPEN + LIST ),
open plot directory ( PIG + OPEN + FIXTURE ).

**Comment by krocheck** [comment]
Do those key combinations work through TouchOSC?  When you say "but works with indiv. single buttons" do you mean that if you map them the 2+ keys to individual banks/buttons on the Stream Deck and press them together it works but when you stack them on the same bank/button they don't work?  Are you using any delay when stacking?

**Comment by Lichtbau** [comment]
don't know about TouchOSC.
yes, those combinations work as you describe with 2+ keys but not stacked together.
i checked OSC input on the hedgehog. incomming OSC looks the same for me.
no delay used.

**Comment by krocheck** [comment]
I would suggest when stacking to put a 5-10ms delay on the 2nd key both press and release.  Let me know if you get the same result.

**Comment by Lichtbau** [comment]
e.g. PIG + FIXTURE gives me the plot keyword in the commandline of the hedgehog.
the trick in a stack is either NOT to release the pig key or to give the key-up-action of the pig key a 10ms delay. than it works fine. thanks for the hint !
![pig fixture working as stack in streamdeck](https://user-images.githubusercontent.com/9751733/51058472-28591200-15e9-11e9-813c-538bb3298868.PNG)
![pig fixture working as stack in streamdeck_2](https://user-images.githubusercontent.com/9751733/51058550-73732500-15e9-11e9-95fe-d9857c4c52e1.PNG)

**Comment by Lichtbau** [comment]
FYI
1st image is PIG+FIXTURE send as stack in streamdeck.
2nd image is PIG+FIXTURE send wth 2 keys in streamdeck.
![pig fixture send as stack in streamdeck](https://user-images.githubusercontent.com/9751733/51058692-e2507e00-15e9-11e9-8163-69abc2bce8f9.PNG)
![pig fixture send wth 2 keys in streamdeck](https://user-images.githubusercontent.com/9751733/51058694-e2507e00-15e9-11e9-933c-42563a529431.PNG)

**Comment by Lichtbau** [comment]
....just the the key down/on actions are shown im the midi viewer.

**Comment by krocheck** [comment]
Copy that.  I'm going to close this out.  Just open up new issues in this repo if you see a bug or think we're still missing something.  Feedback for fader levels, LEDs, and h key text are in my roadmap but there's some things in the Companion core that the guys want to button up first to accept OSC feedback.
