### ISSUE TITLE
HOG 4 virtual buttons in Companion

### ISSUE THREAD

**Issue by patu97** [bitfocus/companion-module-highend-hog4#5]
Hi!

Is there coming more virtual buttons in the Companion's HOG 4 template? In example Park. How about batches? Are they coming in the fader features?

One question about the "H Key's". What are they?

Regards
Patrik

**Comment by josephdadams** [comment]
@patu97 I've transferred this to the HOG module repository.

**Comment by krocheck** [comment]
@patu97 at this point the Hog4 module has implemented 100% of the control spec that High End shows in the manual (control, but not feedback).  Beyond that I don't know much about Hog4 besides being able to program basic stage wash and uplight stuff.

**Comment by halore** [comment]
The H keys are the 12 user definable keys
So there is h1...h12
These keys also have 2 lines of labels which would be great to have as feedback

Re the question from patu97.
The option for batches etc is nothing that can be controlled via osc. These are software features.
The request about keys like park etc: these keys are all softkeys and not mapped to OSC.
