### ISSUE TITLE
Hog4 3.14.0 Update?

### ISSUE THREAD

**Issue by themediaguy1297** [bitfocus/companion-module-highend-hog4#8]
Will this module need to be updated for this new update for Hog?

"Hog 4 PC: Free Control of Hog Faders/Encoders via MIDI and OSC"
https://www.highend.com/pub/support/controllers/release_notes/Hog4_v3-14-0-b3042_releasenotes.pdf

**Comment by krocheck** [comment]
Shouldn't.  I think OSC was limited to physical desks and they've now extended that feature to the PC version.
